# Generated by Django 2.2.16 on 2022-11-18 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^((7)+([0-9]){10})$', message='wor')])),
                ('code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('time_zone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_send_time', models.DateTimeField()),
                ('text', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('end_send_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SEND', 'message has been sent'), ('FAILED', 'message failed'), ('PROCESSED', 'message is being processed')], max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.Contact')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.Mailing')),
            ],
        ),
    ]
