# Generated by Django 2.2.16 on 2022-11-18 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221118_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]){3})$', message='Введите код в формате XXX')], verbose_name='Код телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^((7)+([0-9]){10})$', message='Введите номер в формате 7XXXXXXXXXX')], verbose_name='Номер телефона'),
        ),
    ]
